/**
 * Credential Collector — Phase 1 interactive credential prompt runner.
 *
 * Orchestrates the second-pass prompt phase that runs after stack selection.
 * For each selected module that has a CredentialGroup defined in credentials.ts,
 * it prompts the user for each field, validates input, applies auto-generation
 * for blank secret fields, and resolves derived fields.
 *
 * Returns a CollectedCredentials object that separates:
 *   - `envVars`     — all key/value pairs for .env
 *   - `exampleVars` — redacted pairs for .env.example (secrets replaced with placeholder)
 *
 * @module prompt/credential-collector
 */

import crypto from "node:crypto";
import chalk from "chalk";
import type { PromptAdapter } from "./graph.js";
import {
  getRequiredCredentialGroups,
  type CredentialField,
  type GenerateStrategy,
} from "./credentials.js";
import { printSection } from "../ui/renderer.js";

// ── Types ──────────────────────────────────────────────────────────────────────

export interface CollectedCredentials {
  /**
   * All collected key=value pairs, including generated and derived values.
   * Written verbatim to .env (never committed).
   */
  readonly envVars: Readonly<Record<string, string>>;
  /**
   * Safe-to-commit pairs for .env.example.
   * Secret fields are replaced with a placeholder description.
   * Non-secret fields retain their actual values.
   */
  readonly exampleVars: Readonly<Record<string, string>>;
}

// ── Auto-generate strategies ───────────────────────────────────────────────────

function generateValue(strategy: GenerateStrategy): string {
  switch (strategy) {
    case "random-hex-32":
      return crypto.randomBytes(32).toString("hex");
    case "random-hex-64":
      return crypto.randomBytes(64).toString("hex");
    case "uuid":
      return crypto.randomUUID();
  }
}

function redactSecret(value: string): string {
  if (!value) return value;

  // redact password inside URI formats
  return value.replace(/:\/\/([^:]+):([^@]+)@/, "://$1:<redacted>@");
}
// ── Mask helper ────────────────────────────────────────────────────────────────

/** Returns a placeholder string for .env.example for a secret field. */
function examplePlaceholder(field: CredentialField): string {
  if (field.generate) return `<auto-generated — leave blank to generate>`;
  return `<your-${field.envKey.toLowerCase().replace(/_/g, "-")}>`;
}

// ── Core collector ─────────────────────────────────────────────────────────────

/**
 * Runs the credential prompt phase for all selected modules that require
 * credentials, then returns the collected env vars split into .env and
 * .env.example shapes.
 *
 * @param selectionValues  Ordered array of raw selection values (from RawSelections)
 * @param adapter          PromptAdapter to use for interactive prompts
 * @param ciMode           When true, skip interactive prompts (use defaults / generate)
 */
export async function collectCredentials(
  selectionValues: ReadonlyArray<string>,
  adapter: PromptAdapter,
  ciMode = false,
): Promise<CollectedCredentials> {
  const groups = getRequiredCredentialGroups(selectionValues);

  if (groups.length === 0) {
    return { envVars: {}, exampleVars: {} };
  }

  // Only print the section header if there's something to collect
  printSection("Configuration");

  const envVars: Record<string, string> = {};
  const exampleVars: Record<string, string> = {};

  for (const { group } of groups) {
    // Print group heading
    process.stdout.write(`\n  ${chalk.bold.cyan(group.heading)}\n`);

    // Separate promptable fields from derived fields
    const promptableFields = group.fields.filter((f) => !f.derived);
    const derivedFields = group.fields.filter((f) => !!f.derived);

    // Accumulate raw answers for this group (used to compute derived fields)
    const groupAnswers: Record<string, string> = {};

    for (const field of promptableFields) {
      let value: string;

      if (ciMode) {
        // In CI mode: use default or auto-generate
        if (field.generate) {
          value = generateValue(field.generate);
          process.stdout.write(
            `  ${chalk.dim(`${field.envKey}`)} ${chalk.green("(auto-generated)")}  \n`,
          );
        } else {
          value = field.defaultValue ?? "";
        }
      } else {
        // Interactive mode
        const promptLabel = field.mask ? `${field.label} ${chalk.dim("(hidden)")}` : field.label;

        if (field.mask) {
          // Use a masking transformer — the stored value is NOT transformed,
          // only the display while typing is masked.
          value = await adapter.text({
            message: promptLabel,
            ...(field.defaultValue !== undefined && { defaultValue: field.defaultValue }),
            ...(field.validate && { validate: field.validate }),
            transformer: (v: string) => (v.length > 0 ? "*".repeat(v.length) : ""),
          });
        } else {
          value = await adapter.text({
            message: field.label,
            ...(field.defaultValue !== undefined && { defaultValue: field.defaultValue }),
            ...(field.validate && { validate: field.validate }),
          });
        }

        // Apply auto-generation if user left blank and field supports it
        if (value.trim() === "" && field.generate) {
          value = generateValue(field.generate);
          process.stdout.write(
            `  ${chalk.dim(`→ ${field.envKey}`)} ${chalk.green("auto-generated")}\n`,
          );
        }
      }

      groupAnswers[field.envKey] = value;
      envVars[field.envKey] = value;

      if (field.secret) {
        exampleVars[field.envKey] = examplePlaceholder(field);
      } else {
        exampleVars[field.envKey] = redactSecret(value);
      }
    }

    // Resolve derived fields
    for (const field of derivedFields) {
      const value = field.derived!(groupAnswers);
      envVars[field.envKey] = value;
      // Derived vars (like DATABASE_URL) go into .env.example with the real
      // computed value, since they're assembled from already-exposed parts.
      // Exception: if any component was secret, mask the derived value too.
      const hasSecretComponent = promptableFields.some((f) => f.secret);
      exampleVars[field.envKey] = hasSecretComponent ? examplePlaceholder(field) : value;
    }
  }

  process.stdout.write("\n");

  return {
    envVars: Object.freeze(envVars),
    exampleVars: Object.freeze(exampleVars),
  };
}

