import type { PluginDefinition } from "@systemlabs/foundation-plugin-sdk";

const NEXT_APP_LAYOUT = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "<%= projectName %>",
  description: "Generated by Foundation CLI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

const NEXT_APP_PAGE = `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to <%= projectName %></h1>
      <p className="mt-4 text-gray-600">Your foundation is ready. Start building.</p>
    </main>
  );
}
`;

const NEXT_GLOBALS_CSS = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}
`;

const NEXT_CONFIG = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default nextConfig;
`;

// const TSCONFIG_NEXT = JSON.stringify(
//   {
//     compilerOptions: {
//       target: "ES2017",
//       lib: ["dom", "dom.iterable", "esnext"],
//       allowJs: true,
//       skipLibCheck: true,
//       strict: true,
//       noEmit: true,
//       esModuleInterop: true,
//       module: "esnext",
//       moduleResolution: "bundler",
//       resolveJsonModule: true,
//       isolatedModules: true,
//       jsx: "preserve",
//       incremental: true,
//       plugins: [{ name: "next" }],
//       paths: { "@/*": ["./src/*"] },
//     },
//     include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
//     exclude: ["node_modules"],
//   },
//   null,
//   2,
// );

// const ENV_EXAMPLE = `# Next.js
// NEXT_PUBLIC_APP_URL=http://localhost:3000
// NODE_ENV=development
// `;

export const nextjsModule: PluginDefinition = {
  manifest: {
    id: "frontend-nextjs",
    name: "Next.js",
    version: "1.0.0",
    description: "Next.js 14 App Router scaffold with TypeScript",
    category: "frontend",

    dependencies: [
      { name: "next", version: "14.2.3", scope: "dependencies" },
      { name: "react", version: "^18.3.1", scope: "dependencies" },
      { name: "react-dom", version: "^18.3.1", scope: "dependencies" },
      { name: "@types/node", version: "^20.0.0", scope: "devDependencies" },
      { name: "@types/react", version: "^18.3.1", scope: "devDependencies" },
      { name: "@types/react-dom", version: "^18.3.1", scope: "devDependencies" },
      { name: "typescript", version: "^5.4.5", scope: "devDependencies" },
    ],

    files: [
      { relativePath: "src/app/layout.tsx", content: NEXT_APP_LAYOUT },
      { relativePath: "src/app/page.tsx", content: NEXT_APP_PAGE },
      { relativePath: "src/app/globals.css", content: NEXT_GLOBALS_CSS },
      { relativePath: "next.config.mjs", content: NEXT_CONFIG },
    ],

    configPatches: [
      {
        targetFile: "package.json",
        merge: {
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
            lint: "next lint",
          },
        },
      },

      {
        targetFile: "tsconfig.json",
        merge: {
          compilerOptions: {
            target: "ES2017",
            allowJs: true,
            skipLibCheck: true,
            strict: true,
            noEmit: true,
            esModuleInterop: true,
            module: "esnext",
            moduleResolution: "bundler",
            resolveJsonModule: true,
            isolatedModules: true,
            jsx: "preserve",
            incremental: true,
            paths: {
              "@/*": ["./src/*"],
            },
          },
        },
      },

      // {
      //   targetFile: "tsconfig.json",
      //   merge: {
      //     compilerOptions: {
      //       paths: {
      //         "@backend/*": ["src/backend/*"],
      //       },
      //     },
      //   },
      // },

      {
        targetFile: ".env.example",
        merge: {
          NEXT_PUBLIC_APP_URL: "http://localhost:3000",
          NODE_ENV: "development",
        },
      },
    ],

    compatibility: {
      conflicts: [],
    },
  },
};

