import type { PluginDefinition } from "@systemlabs/foundation-plugin-sdk";
import type { ORMProvider, ORMModelDefinition, ORMFieldType } from "@systemlabs/foundation-core";
import { registerProviderFromContext } from "./provider-utils";

// ── Template strings ──────────────────────────────────────────────────────────

const DB_TS = `import mongoose from "mongoose";
import { config } from "dotenv";

config();

const MONGODB_URI = process.env["MONGODB_URI"];

if (!MONGODB_URI) {
  throw new Error("MONGODB_URI environment variable is required");
}

let isConnected = false;

export async function connectDB(): Promise<void> {
  if (isConnected) return;

  await mongoose.connect(MONGODB_URI, {
    bufferCommands: false,
  });

  isConnected = true;
  console.log("MongoDB connected");
}

export async function disconnectDB(): Promise<void> {
  if (!isConnected) return;
  await mongoose.disconnect();
  isConnected = false;
}
`;

const USER_MODEL_TS = `import mongoose, { type Document, Schema } from "mongoose";

export interface IUser extends Document {
  email: string;
  createdAt: Date;
  updatedAt: Date;
}

const UserSchema = new Schema<IUser>(
  {
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
  },
  { timestamps: true },
);

export const User = mongoose.models.User ?? mongoose.model<IUser>("User", UserSchema);
`;

// ── ORM Provider ──────────────────────────────────────────────────────────────

/** Maps portable field types to Mongoose SchemaType constructors. */
const MONGOOSE_TYPE_MAP: Record<ORMFieldType, string> = {
  string: "String",
  number: "Number",
  boolean: "Boolean",
  date: "Date",
  uuid: "String",
  json: "Schema.Types.Mixed",
};

/** Maps portable field types to TypeScript interface types. */
const TS_TYPE_MAP: Record<ORMFieldType, string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
  date: "Date",
  uuid: "string",
  json: "Record<string, unknown>",
};

const mongooseProvider: ORMProvider = {
  id: "orm-mongoose",
  name: "Mongoose",

  buildSchemaFiles(models: ReadonlyArray<ORMModelDefinition>) {
    return models.map((model) => {
      const interfaceName = `I${model.name}`;
      const schemaName = `${model.name}Schema`;
      const collectionName = `${model.name.toLowerCase()}s`;

      // Interface fields (skip primaryKey/_id — Mongoose provides it)
      const nonPkFields = model.fields.filter((f) => !f.primaryKey);

      const interfaceFields = nonPkFields.map((field) => {
        const tsType = TS_TYPE_MAP[field.type] ?? "unknown";
        const optional = field.required === false ? "?" : "";
        return `  ${field.name}${optional}: ${tsType};`;
      });

      // Schema fields
      const schemaFields = nonPkFields.map((field) => {
        const mongooseType = MONGOOSE_TYPE_MAP[field.type] ?? "String";
        const opts: string[] = [`type: ${mongooseType}`];
        if (field.required !== false) opts.push("required: true");
        if (field.unique) opts.push("unique: true");
        return `    ${field.name}: { ${opts.join(", ")} },`;
      });

      // ── Relations (Mongoose refs) ─────────────────────────────────────────
      const relationInterfaceFields = (model.relations ?? []).map((rel) => {
        const isArray = rel.type === "one-to-many" || rel.type === "many-to-many";
        return `  ${rel.name}: mongoose.Types.ObjectId${isArray ? "[]" : ""};`;
      });
      const relationSchemaFields = (model.relations ?? []).map((rel) => {
        const isArray = rel.type === "one-to-many" || rel.type === "many-to-many";
        return isArray
          ? `    ${rel.name}: [{ type: Schema.Types.ObjectId, ref: "${rel.target}" }],`
          : `    ${rel.name}: { type: Schema.Types.ObjectId, ref: "${rel.target}" },`;
      });

      const lines: string[] = [
        `// Generated by foundation-cli (source module: ${model.sourceModuleId})`,
        `import mongoose, { type Document, Schema } from "mongoose";`,
        "",
        `export interface ${interfaceName} extends Document {`,
        ...interfaceFields,
        ...relationInterfaceFields,
        `  createdAt: Date;`,
        `  updatedAt: Date;`,
        `}`,
        "",
        `const ${schemaName} = new Schema<${interfaceName}>(`,
        `  {`,
        ...schemaFields,
        ...relationSchemaFields,
        `  },`,
        `  { timestamps: true, collection: "${collectionName}" },`,
        `);`,
        "",
        `export const ${model.name} =`,
        `  mongoose.models.${model.name} ??`,
        `  mongoose.model<${interfaceName}>("${model.name}", ${schemaName});`,
      ];

      return {
        relativePath: `src/models/${model.name}.model.ts`,
        content: lines.join("\n"),
        overwrite: true,
      };
    });
  },
};

// ── Module definition ─────────────────────────────────────────────────────────

export const mongooseModule: PluginDefinition = {
  manifest: {
    id: "orm-mongoose",
    name: "Mongoose",
    version: "1.0.0",
    description: "Mongoose ODM for MongoDB with schema validation and TypeScript support",
    category: "orm",
    provides: ["orm", "database-client"],
    // requires: ["database"],
    runtime: "node",
    compatibility: {
      conflicts: ["orm-prisma", "orm-typeorm", "orm-sqlalchemy"],
      compatibleWith: {
        database: ["database-mongodb"],
      },
    },
    dependencies: [
      { name: "mongoose", version: "^8.4.0", scope: "dependencies" },
      { name: "dotenv", version: "^16.4.5", scope: "dependencies" },
    ],
    files: [
      { relativePath: "src/lib/db.ts", content: DB_TS },
      { relativePath: "src/models/User.model.ts", content: USER_MODEL_TS },
    ],
    configPatches: [
      {
        targetFile: ".env.example",
        merge: {
          MONGODB_URI: "mongodb://localhost:27017/<%= projectName %>",
        },
      },
    ],
    postInstallInstructions:
      "Call `connectDB()` at app startup. " +
      "Mongoose models are auto-registered on first import.",
  },

  hooks: {
    onRegister(ctx): Promise<void> {
      registerProviderFromContext(ctx, mongooseProvider);
      return Promise.resolve();
    },
  },
};