import type { PluginDefinition } from "@systemlabs/foundation-plugin-sdk";
import type { ORMProvider, ORMModelDefinition, ORMFieldType } from "@systemlabs/foundation-core";
import { registerProviderFromContext } from "./provider-utils";

// ── Template strings ──────────────────────────────────────────────────────────

const PRISMA_SCHEMA = `// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id        String   @id @default(cuid())
  email     String   @unique
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}
`;

const DB_TS = `import { PrismaClient } from "@prisma/client";

declare global {
  // eslint-disable-next-line no-var
  var __prisma: PrismaClient | undefined;
}

// Prevent multiple instances of Prisma Client in development
export const db =
  globalThis.__prisma ??
  new PrismaClient({
    log: process.env["NODE_ENV"] === "development" ? ["query", "error", "warn"] : ["error"],
  });

if (process.env["NODE_ENV"] !== "production") {
  globalThis.__prisma = db;
}
`;

// ── ORM Provider ──────────────────────────────────────────────────────────────

/** Maps portable field types to Prisma scalar types. */
const PRISMA_TYPE_MAP: Record<ORMFieldType, string> = {
  string: "String",
  number: "Int",
  boolean: "Boolean",
  date: "DateTime",
  uuid: "String",
  json: "Json",
};

const prismaProvider: ORMProvider = {
  id: "orm-prisma",
  name: "Prisma",

  buildSchemaFiles(models: ReadonlyArray<ORMModelDefinition>) {
    if (models.length === 0) return [];

    const modelBlocks = models.map((model) => {
      const lines: string[] = [
        `// Generated by foundation-cli (source module: ${model.sourceModuleId})`,
        `model ${model.name} {`,
      ];

      for (const field of model.fields) {
        const prismaType = PRISMA_TYPE_MAP[field.type] ?? "String";
        const nullable = field.required === false ? "?" : "";
        const attrs: string[] = [];

        if (field.primaryKey) {
          attrs.push("@id");
          if (field.generated) {
            attrs.push(field.type === "uuid" ? "@default(cuid())" : "@default(autoincrement())");
          }
        } else {
          if (field.generated && field.type === "date") attrs.push("@default(now())");
          if (field.generated && field.type === "uuid") attrs.push("@default(cuid())");
        }

        if (field.unique && !field.primaryKey) attrs.push("@unique");

        const attrStr = attrs.length > 0 ? `  ${attrs.join(" ")}` : "";
        lines.push(`  ${field.name.padEnd(14)} ${prismaType}${nullable}${attrStr}`);
      }

      // ── Relations ────────────────────────────────────────────────────────────
      for (const rel of model.relations ?? []) {
        const fk = rel.foreignKey ?? `${rel.name}Id`;
        if (rel.type === "many-to-one" || rel.type === "one-to-one") {
          lines.push(`  ${rel.name.padEnd(14)} ${rel.target}  @relation(fields: [${fk}], references: [id]${rel.cascade ? ", onDelete: Cascade" : ""})`);
          lines.push(`  ${fk.padEnd(14)} String`);
        } else if (rel.type === "one-to-many") {
          lines.push(`  ${rel.name.padEnd(14)} ${rel.target}[]`);
        } else if (rel.type === "many-to-many") {
          lines.push(`  ${rel.name.padEnd(14)} ${rel.target}[]`);
        }
      }

      lines.push("}");
      return lines.join("\n");
    });

    // Append generated model blocks after the base schema.
    const appendedSchema = PRISMA_SCHEMA.trimEnd() + "\n\n" + modelBlocks.join("\n\n") + "\n";

    return [{ relativePath: "prisma/schema.prisma", content: appendedSchema, overwrite: true }];
  },
};

// ── Module definition ─────────────────────────────────────────────────────────

export const prismaModule: PluginDefinition = {
  manifest: {
    id: "orm-prisma",
    name: "Prisma",
    version: "1.0.0",
    description: "Prisma ORM with type-safe database client and migrations",
    category: "orm",
    provides: ["orm", "database-client"],
    // requires: ["database"],
    runtime: "node",
    compatibility: {
      conflicts: ["orm-typeorm", "orm-mongoose"],
      compatibleWith: {
        database: ["database-postgresql", "database-mysql", "database-sqlite", "database-mongodb"],
      },
    },
    dependencies: [
      { name: "@prisma/client", version: "^5.14.0", scope: "dependencies" },
      { name: "prisma", version: "^5.14.0", scope: "devDependencies" },
    ],
    files: [
      { relativePath: "prisma/schema.prisma", content: PRISMA_SCHEMA },
      { relativePath: "src/lib/db.ts", content: DB_TS },
    ],
    configPatches: [
      {
        targetFile: "package.json",
        merge: {
          scripts: {
            "db:generate": "prisma generate",
            "db:migrate": "prisma migrate dev",
            "db:studio": "prisma studio",
            "db:push": "prisma db push",
          },
        },
      },
      {
        targetFile: ".env.example",
        merge: {
          DATABASE_URL: "postgresql://user:password@localhost:5432/<%= projectName %>",
        },
      },
    ],
    postInstallInstructions:
      "Run `npm run db:migrate` to apply your first migration, " +
      "then `npm run db:generate` to regenerate the Prisma client.",
  },

  hooks: {
    /**
     * Registers the Prisma ORM provider with the active registry's ORMService.
     * Called once per registry during module loading.
     */
    onRegister(ctx): Promise<void> {
      registerProviderFromContext(ctx, prismaProvider);
      return Promise.resolve();
    },
  },
};