import type { PluginDefinition } from "@systemlabs/foundation-plugin-sdk";
import type { ORMProvider, ORMModelDefinition, ORMFieldType } from "@systemlabs/foundation-core";
import { registerProviderFromContext } from "./provider-utils";

// ── Template strings ──────────────────────────────────────────────────────────

const DATA_SOURCE_TS = `import "reflect-metadata";
import { DataSource } from "typeorm";
import { config } from "dotenv";

config();

export const AppDataSource = new DataSource({
  type: "postgres",
  url: process.env["DATABASE_URL"],
  ssl: process.env["NODE_ENV"] === "production" ? { rejectUnauthorized: false } : false,
  synchronize: process.env["NODE_ENV"] !== "production",
  logging: process.env["NODE_ENV"] === "development",
  entities: ["src/entities/**/*.ts"],
  migrations: ["src/migrations/**/*.ts"],
  subscribers: [],
});
`;

const USER_ENTITY_TS = `import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  CreateDateColumn,
  UpdateDateColumn,
} from "typeorm";

@Entity("users")
export class User {
  @PrimaryGeneratedColumn("uuid")
  id!: string;

  @Column({ unique: true })
  email!: string;

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
`;

// ── ORM Provider ──────────────────────────────────────────────────────────────

/** Maps portable field types to TypeScript primitive types. */
const TS_TYPE_MAP: Record<ORMFieldType, string> = {
  string: "string",
  number: "number",
  boolean: "boolean",
  date: "Date",
  uuid: "string",
  json: "Record<string, unknown>",
};

const typeormProvider: ORMProvider = {
  id: "orm-typeorm",
  name: "TypeORM",

  buildSchemaFiles(models: ReadonlyArray<ORMModelDefinition>) {
    return models.map((model) => {
      const decoratorImports = new Set<string>(["Entity"]);
      const fieldLines: string[] = [];

      for (const field of model.fields) {
        const tsType = TS_TYPE_MAP[field.type] ?? "unknown";

        if (field.primaryKey) {
          decoratorImports.add("PrimaryGeneratedColumn");
          fieldLines.push(`  @PrimaryGeneratedColumn("uuid")`);
          fieldLines.push(`  ${field.name}!: string;`);
        } else if (field.type === "date" && field.generated) {
          decoratorImports.add("CreateDateColumn");
          fieldLines.push(`  @CreateDateColumn()`);
          fieldLines.push(`  ${field.name}!: Date;`);
        } else {
          decoratorImports.add("Column");
          const colOpts = field.unique ? `{ unique: true }` : ``;
          fieldLines.push(`  @Column(${colOpts})`);
          fieldLines.push(`  ${field.name}!: ${tsType};`);
        }
        fieldLines.push("");
      }

      // Always add standard timestamp columns if none were declared.
      const hasCreatedAt = model.fields.some((f) => f.name === "createdAt");
      const hasUpdatedAt = model.fields.some((f) => f.name === "updatedAt");

      if (!hasCreatedAt) {
        decoratorImports.add("CreateDateColumn");
        fieldLines.push(`  @CreateDateColumn()`);
        fieldLines.push(`  createdAt!: Date;`);
        fieldLines.push("");
      }
      if (!hasUpdatedAt) {
        decoratorImports.add("UpdateDateColumn");
        fieldLines.push(`  @UpdateDateColumn()`);
        fieldLines.push(`  updatedAt!: Date;`);
        fieldLines.push("");
      }

      // ── Relations ────────────────────────────────────────────────────────────
      for (const rel of model.relations ?? []) {
        if (rel.type === "many-to-one") {
          decoratorImports.add("ManyToOne");
          fieldLines.push(`  @ManyToOne(() => ${rel.target}${rel.cascade ? `, { cascade: true }` : ""})`);
          fieldLines.push(`  ${rel.name}!: ${rel.target};`);
          fieldLines.push("");
        } else if (rel.type === "one-to-many") {
          decoratorImports.add("OneToMany");
          fieldLines.push(`  @OneToMany(() => ${rel.target}, (item) => item.${model.name.toLowerCase()})`);
          fieldLines.push(`  ${rel.name}!: ${rel.target}[];`);
          fieldLines.push("");
        } else if (rel.type === "one-to-one") {
          decoratorImports.add("OneToOne");
          fieldLines.push(`  @OneToOne(() => ${rel.target}${rel.cascade ? `, { cascade: true }` : ""})`);
          fieldLines.push(`  ${rel.name}!: ${rel.target};`);
          fieldLines.push("");
        } else if (rel.type === "many-to-many") {
          decoratorImports.add("ManyToMany");
          fieldLines.push(`  @ManyToMany(() => ${rel.target})`);
          fieldLines.push(`  ${rel.name}!: ${rel.target}[];`);
          fieldLines.push("");
        }
      }

      const importLine = `import { ${Array.from(decoratorImports).sort().join(", ")} } from "typeorm";`;
      const tableName = `${model.name.toLowerCase()}s`;

      const lines: string[] = [
        `// Generated by foundation-cli (source module: ${model.sourceModuleId})`,
        importLine,
        "",
        `@Entity("${tableName}")`,
        `export class ${model.name} {`,
        ...fieldLines,
        "}",
      ];

      return {
        relativePath: `src/entities/${model.name}.entity.ts`,
        content: lines.join("\n"),
        overwrite: true,
      };
    });
  },
};

// ── Module definition ─────────────────────────────────────────────────────────

export const typeormModule: PluginDefinition = {
  manifest: {
    id: "orm-typeorm",
    name: "TypeORM",
    version: "1.0.0",
    description: "TypeORM with decorators and Active Record / Data Mapper patterns",
    category: "orm",
    provides: ["orm", "database-client"],
    // requires: ["database"],
    runtime: "node",
    compatibility: {
      conflicts: ["orm-prisma", "orm-mongoose", "orm-sqlalchemy"],
    },
    dependencies: [
      { name: "typeorm", version: "^0.3.20", scope: "dependencies" },
      { name: "reflect-metadata", version: "^0.2.2", scope: "dependencies" },
      { name: "pg", version: "^8.11.5", scope: "dependencies" },
      { name: "dotenv", version: "^16.4.5", scope: "dependencies" },
    ],
    files: [
      { relativePath: "src/data-source.ts", content: DATA_SOURCE_TS },
      { relativePath: "src/entities/User.entity.ts", content: USER_ENTITY_TS },
    ],
    configPatches: [
      {
        targetFile: "package.json",
        merge: {
          scripts: {
            "migration:run": "typeorm migration:run -d src/data-source.ts",
            "migration:revert": "typeorm migration:revert -d src/data-source.ts",
          },
        },
      },
      {
        targetFile: "tsconfig.json",
        merge: {
          compilerOptions: {
            experimentalDecorators: true,
            emitDecoratorMetadata: true,
          },
        },
      },
      {
        targetFile: ".env.example",
        merge: {
          DATABASE_URL: "postgresql://user:password@localhost:5432/<%= projectName %>",
        },
      },
    ],
    postInstallInstructions:
      "Add `import 'reflect-metadata'` at the top of your entry file. " +
      "Run `npm run migration:run` to sync your schema.",
  },

  hooks: {
    onRegister(ctx): Promise<void> {
      registerProviderFromContext(ctx, typeormProvider);
      return Promise.resolve();
    },
  },
};